# apiVersion: v1
# kind: Service
# metadata:
#   name: devops-fusion-webapi
# spec:
#   type: NodePort
#   selector:
#     app: devops-fusion-webapi
#   ports:
#     - protocol: TCP
#       port: 8080        
#       targetPort: 8080  
#       nodePort: 30000   
apiVersion: v1
kind: Service
metadata:
  name: devops-fusion-webapi
spec:
  type: LoadBalancer
  selector:
    app: devops-fusion-webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080