apiVersion: v1
kind: Service
metadata:
  name: devops-fusion-webapi
spec:
  type: LoadBalancer
  selector:
    app: devops-fusion-webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080