apiVersion: v1
kind: Service
metadata:
  name: devops-fusion-webapi-service
spec:
  selector:
    app: devops-fusion-webapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP