name: CI/CD Minikube Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6.10.0
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops.fusion.webapi:${{ github.sha }}
          context: ./devops.fusion.webapi
          file: ./devops.fusion.webapi/Dockerfile

      - name: Set up Minikube
        uses: sagikazarmark/setup-minikube-action@v0

      - name: Launch Minikube Cluster
        run: minikube start

      - name: Load Docker Image into Minikube
        run: |
          minikube image load ${{ secrets.DOCKER_USERNAME }}/devops.fusion.webapi:${{ github.sha }}

      - name: Replace Placeholders in Manifests
        run: |
          sed -i "s|\${DOCKER_USERNAME}|${{ secrets.DOCKER_USERNAME }}|g" ./deployment/deployment.yaml
          sed -i "s|\${GITHUB_SHA}|${{ github.sha }}|g" ./deployment/deployment.yaml

      - name: Deploy to Minikube
        run: |
          kubectl apply -f ./deployment/deployment.yaml
          kubectl apply -f ./deployment/service.yaml

      - name: Wait for Application to Be Ready
        run: kubectl rollout status deployment/devops-fusion-webapi

      - name: Start Minikube Tunnel
        run: |
          nohup minikube tunnel > /dev/null 2>&1 &
          sleep 10

      - name: Get Load Balancer External IP
        run: |
          LB_IP=$(kubectl get svc devops-fusion-webapi -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Application is accessible at http://$LB_IP"
          curl http://$LB_IP/weatherforecast
