name: CI/CD Minikube Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Minikube
        uses: sagikazarmark/setup-minikube-action@v0

      - name: Launch Minikube Cluster
        run: |
          minikube start --driver=docker

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4.0.0
        with:
          version: 'latest'

      - name: Build Docker Image
        uses: docker/build-push-action@v6.10.0
        with:
          push: false
          tags: devops.fusion.webapi:latest
          context: .  # Adjust this if your Dockerfile is in a subfolder
          file: ./devops.fusion.webapi/Dockerfile  # Adjust the path if the Dockerfile is in a subfolder


      - name: Apply Kubernetes Configuration
        run: |
          kubectl apply -f deployment/deployment.yaml
          kubectl apply -f deployment/service.yaml

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
