name: CI/CD Minikube Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6.10.0
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops.fusion.webapi:${{ github.sha }}
          context: ./devops.fusion.webapi
          file: ./devops.fusion.webapi/Dockerfile

      # Set up Minikube
      - name: Set up Minikube
        uses: sagikazarmark/setup-minikube-action@v0

      # Start Minikube
      - name: Launch Minikube Cluster
        run: minikube start

      # Debugging: Verify Minikube Cluster
      - name: Verify Minikube Nodes
        run: kubectl get nodes

      # Load Docker image into Minikube
      - name: Load Docker Image into Minikube
        run: |
          minikube image load ${{ secrets.DOCKER_USERNAME }}/devops.fusion.webapi:${{ github.sha }}

      # Debugging: Verify Image in Minikube
      - name: List Minikube Images
        run: minikube image list

      # Apply Kubernetes manifests
      - name: Deploy to Minikube
        run: |
          kubectl apply -f ./deployment/deployment.yaml
          kubectl apply -f ./deployment/service.yaml

      # Debugging: Check Pod Status
      - name: Get Pod Status
        run: kubectl get pods -o wide

      # Debugging: Describe Pod for Details
      - name: Describe Pod
        run: |
          POD_NAME=$(kubectl get pods -l app=devops-fusion-webapi -o jsonpath='{.items[0].metadata.name}')
          kubectl describe pod $POD_NAME

      # Debugging: Check Kubernetes Events
      - name: Get Events
        run: kubectl get events --sort-by=.metadata.creationTimestamp

      # Wait for Deployment to Be Ready
      - name: Wait for Application to Be Ready
        run: kubectl rollout status deployment/devops-fusion-webapi

      # Debugging: Check Logs if Rollout Fails
      - name: Get Logs
        if: failure()
        run: |
          POD_NAME=$(kubectl get pods -l app=devops-fusion-webapi -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $POD_NAME

      # Access the Application
      - name: Access the Application
        run: |
          minikube service devops-fusion-webapi --url

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}