name: CI/CD Minikube Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6.10.0
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops.fusion.webapi:${{ github.sha }}
          context: ./devops.fusion.webapi
          file: ./devops.fusion.webapi/Dockerfile

      # Set up Minikube
      - name: Set up Minikube
        uses: sagikazarmark/setup-minikube-action@v0

      # Start Minikube
      - name: Launch Minikube Cluster
        run: minikube start

      # Load Docker image into Minikube
      - name: Load Docker Image into Minikube
        run: |
          minikube image load ${{ secrets.DOCKER_USERNAME }}/devops.fusion.webapi:${{ github.sha }}

      # Apply Kubernetes manifests
      - name: Deploy to Minikube
        run: |
          kubectl apply -f ./deployment/deployment.yaml
          kubectl apply -f ./deployment/service.yaml

      # Wait for Deployment to Be Ready
      - name: Wait for Application to Be Ready
        run: |
          kubectl rollout status deployment/devops-fusion-webapi

      # Access the Application
      - name: Access the Application
        run: |
          minikube service devops-fusion-webapi --url

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}