name: CI/CD Minikube Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Minikube
        uses: sagikazarmark/setup-minikube-action@v0

      - name: Launch Minikube Cluster
        run: minikube start

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  # Or DOCKER_ACCESS_TOKEN

      - name: Build Docker Image
        uses: docker/build-push-action@v6.10.0
        with:
          push: true  # Set this to 'true' to push the image to DockerHub
          tags: ${{ secrets.DOCKER_USERNAME }}/devops.fusion.webapi:${{ github.sha }}
          context: ./devops.fusion.webapi
          file: ./devops.fusion.webapi/Dockerfile

      - name: Load Docker Image into Minikube
        run: minikube image load ${{ secrets.DOCKER_USERNAME }}/devops.fusion.webapi:${{ github.sha }}

      - name: Apply Kubernetes Configuration
        run: |
          kubectl apply -f deployment/deployment.yaml
          kubectl apply -f deployment/service.yaml
      
      - name: Check Pod Status
        run: kubectl get pods

      - name: Describe Deployment
        run: kubectl describe deployment devops-fusion-webapi

      - name: Wait for Pods to be Running
        run: |
          kubectl rollout status deployment/devops-fusion-webapi
          kubectl get pods

      - name: Get Service URL
        run: |
          minikube service my-app --url
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
