name: CI/CD Minikube Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2  # Updated version

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2.13.0  # Updated version
        with:
          minikube-version: 'latest'
          kubernetes-version: '1.32.0'  # Updated version
          driver: docker

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4.0.0  # Updated version
        with:
          version: 'latest'

      - name: Build Docker Image
        uses: docker/build-push-action@v6.10.0  # Updated version
        with:
          push: false
          tags: devops.fusion.webapi:latest

      - name: Apply Kubernetes Configuration
        run: |
          kubectl apply -f deployment/deployment.yaml
          kubectl apply -f deployment/service.yaml
