name: CI/CD Minikube Deployment

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Minikube
        uses: sagikazarmark/setup-minikube-action@v0

      - name: Launch Minikube Cluster
        run: minikube start

      - name: Build Docker Image
        uses: docker/build-push-action@v6.10.0
        with:
          push: true  # Push to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/devops.fusion.webapi:${{ github.sha }}
          context: ./devops.fusion.webapi
          file: ./devops.fusion.webapi/Dockerfile

      - name: Apply Kubernetes Configuration
        run: |
          kubectl apply -f deployment/deployment.yaml
          kubectl apply -f deployment/service.yaml

      - name: Wait for Pods to be Running
        run: |
          kubectl rollout status deployment/devops-fusion-webapi
          kubectl get pods

      - name: Get Service URL
        run: |
          minikube service my-app --url

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
